import { prismaThread } from '../src/lib/prisma-thread';

async function main() {
  try {
    console.log('Connecting to Thread DB...');

    // Check if we have any threads
    let thread = await prismaThread.threads.findFirst();

    if (!thread) {
      console.log('No threads found. Creating a dummy thread...');
      // Need a valid user_id. Assuming 1 exists or is acceptable for dummy.
      // If validation fails, we might need a real user. But usually int FKs are not enforced across DBs unless strictly defined in same DB.
      // In this schema, user_id is Int.
      thread = await prismaThread.threads.create({
        data: {
          user_id: 1,
          content: 'This is a dummy thread for testing reports.',
          visibility: 'public',
          parent_level: 0
        }
      });
      console.log('Created dummy thread:', thread.id);
    } else {
      console.log('Found existing thread:', thread.id);
    }

    // Create a report
    console.log('Creating a dummy report...');
    const report = await prismaThread.threadReports.create({
      data: {
        threads_id: thread.id,
        reported_by: 1, // Dummy Reporter ID
        reason: 'This is a test report generated by seed script.'
      }
    });

    console.log('Created report:', report);
    console.log('Seed completed successfully.');
  } catch (e) {
    console.error('Error seeding data:', e);
  } finally {
    await prismaThread.$disconnect();
  }
}

main();
